#!/usr/bin/env bash


#FIXME definir una variable del estilo ECLIPSE_HOME
#chequeo si existe el archivo eclipse, asumo que es una distribución de eclipse
[ -e eclipse  ] || (echo "Este script se ejecuta desde el directorio de Eclipse. copiar este $0 y p2-repo" && exit 1)

set -e
set -u

#latest base-lib
base_lib_module="../bundles/base.lib"
(cd $base_lib_module && mvn verify package)
#se genera un solo bundle/jar, el que corresponde
base_lib_jar=$base_lib_module/target/*.jar


launcher=plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar
target_repository=file:$(pwd)/p2-repo/target/repository

repo_source="/tmp/source~$RANDOM"
#se requiere que el bundle esté dentro del directorio plugins
mkdir -p $repo_source/plugins

cp $base_lib_jar $repo_source/plugins

rm -rf $target_repository

java -jar $launcher \
  -data /tmp/ws-$RANDOM \
  -application org.eclipse.equinox.p2.publisher.FeaturesAndBundlesPublisher \
  -metadataRepository $target_repository \
  -artifactRepository $target_repository \
  -source $repo_source \
  -compress \
  -publishArtifacts

category_file="file:$(pwd)/category.xml"
java -jar $launcher \
  -application org.eclipse.equinox.p2.publisher.CategoryPublisher \
  -data /tmp/ws-$RANDOM \
  -metadataRepository $target_repository \
  -categoryDefinition $category_file


cd p2-repo 
mvn jetty:run &
echo $! > jetty.pid

