#!/usr/bin/env bash

set -u

site=http://localhost:8080/site/artifacts.jar

artifactId=edu.medicine.bioplat.base.lib

curl --silent http://localhost:8080/site/artifacts.jar |zcat >& /dev/null 
if [ $? != 0 ];then
  echo No se encontró el repositorio p2 en $site 
  exit -10
fi

version=$(curl --silent $site | zcat | grep "id='$artifactId'" | cut -d= -f4 | cut -d\' -f2 )

target_location=$(cat << _EOF
<location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit"> 
<unit id="edu.medicine.bioplat.base.lib" version="$version"/> 
<repository location="http://localhost:8080/site/"/>
</location>
_EOF
)

orig="releng/org.bioplat.target/org.bioplat.target.target"
target=/tmp/$RANDOM
cp $orig $target



function replace {
    sed -i "s/$(echo $1 | sed -e 's/\([[\/.*]\|\]\)/\\&/g')/$(echo $2 | sed -e 's/[\/&]/\\&/g')/g" $3
}


placeholder_mark="<!-- base-lib-placeholder -->"
if cat $target | grep "$placeholder_mark" > /dev/null; then
   replace "$placeholder_mark" "$target_location" "$target"
   mv $orig{,.bkp}
   mv $target $orig
   echo "$orig modificado. Bioplat base lib $version configurado a versión $version. (este archivo no se comitea)"
else
  echo "No está el placeholder '$placeholder_mark' en $target (->$orig)"
  exit 1
fi

