#!/usr/bin/env bash


#FIXME revisar que el working directory esté limpio
#FIXME si hay un tag para el commit actual tiene precedencia. en ese caso debería igual devolver el commit id. 
git_info(){
  #busco el tag 
  info=$(git describe --exact-match --tags $(git log -n1 --pretty='%h') 2>/dev/null)
  if [ $? != 0   ];then
    #si no hay tag uso el commit id y la fecha
    date=$(date +%Y%m%d)
    commit_id=$(git rev-parse --short HEAD)
    info="$date~$commit_id"
  fi
  echo $info
}

version=$1
if [ -z "$version"  ];then
  version=$(git_info)
  echo "calculated version -> $version"
fi

(echo -n "Publicando repo p2 con base lib" && cd eclipse-minimal && ./base-lib-p2-publisher >/dev/null &)

while ! curl --silent http://localhost:8080/site/artifacts.jar > /dev/null ;do
  echo -n "."
  sleep 10s
done
echo ""

./add-base-lib-to-target-definition && \
mvn clean package && 
./run-post-package-tools $version && \
mvn --offline clean

kill $(cat eclipse-minimal/p2-repo/jetty.pid)

